// Today's Line generation (Audit-5 · 03 §3). A direct sibling of `_shared/fortune.ts`, and
// deliberately so: same worker-pool-with-resume shape, same "a partial day is a FAILED day" verdict,
// same injectable seams (geminiCall / existing / upsert) so the whole thing is unit-testable with no
// network and no DB.
//
// What differs from the fortune generator, and why: the fan-out is per FEATURE, not per birth-date
// bucket — 15 rows a day instead of 61, because the day-pillar belongs to the DATE. That is a ~4×
// cost drop AND it makes birth date optional for this feature, which is the point (03 §2.1).
import AjvDefault from 'ajv';
import pulseSchema from '../../../schemas/pulse.v1.json' with { type: 'json' };
import { toGeminiSchema } from './schema.ts';
import { bannedHits, type GeminiCall, type GeminiResponse } from './narrative.ts';
import { fnv1a, PULSE_FEATURE_KEYS } from './pulse.ts';

export const PULSE_MODEL = 'gemini-3.1-flash-lite';
/**
 * v2 (Audit-5 RF6.T1) — the reframe. v1 made the day-pillar the subject of every `essence`, and the
 * live eval showed fifteen features coming back as one sentence with the nouns swapped (05 §0). v2
 * makes the FEATURE the grammatical subject and bans the day's name from the free line entirely.
 * Bumped in lockstep with the import in `pulse-generate/index.ts` — the stamp must never name a
 * prompt version the function did not actually send.
 */
export const PULSE_PROMPT_VERSION = 'pulse.v2';
/** Next in the pinned-seed series (extraction 7 / narrative 11 / fortune 13). */
export const PULSE_SEED = 17;
/** Same pool size as the fortune run — 15 features is ~3 waves. */
export const PULSE_CONCURRENCY = 6;

/**
 * The human name each feature goes by in prose and in the push. The model is given this so it never
 * has to guess how to say `hand_shape` out loud, and the push copy reuses the same table so the
 * notification and the card name the feature identically.
 */
export const FEATURE_LABEL: Record<string, string> = {
  heart: 'heart line',
  head: 'head line',
  life: 'life line',
  fate: 'fate line',
  hand_shape: 'hand shape',
  mounts: 'mounts',
  markings: 'markings',
  face_shape: 'elemental face',
  proportion: 'proportions',
  eyes: 'eyes',
  eyebrows: 'brows',
  nose: 'nose',
  mouth: 'mouth',
  ears: 'ears',
  canthus: 'under-eye',
};

/**
 * The fifteen sentence shapes for `essence`, and why they are assigned by the CALLER (RF6.T1).
 *
 * The day's fifteen features are generated by fifteen INDEPENDENT calls sharing one system prompt
 * and one pinned seed. A prompt rule like "no two features may open the same way" is therefore not
 * a rule the model can obey — it cannot see the other fourteen. Left free, it converges: v1 gave
 * fifteen variants of "<feature> <verb>s under the <pillar> day", and v2's first draft gave five of
 * "prefers the quiet X over Y" and five of "holds its X while the air grows restless".
 *
 * So the shape is chosen HERE, by a per-date permutation, and passed in the payload. Fifteen shapes
 * over fifteen features means every feature on a given day gets a different construction by
 * construction, and the assignment reshuffles daily so a feature never wears one shape as a habit.
 */
export const PULSE_SHAPES: readonly string[] = [
  'disposition',
  'already_decided',
  'flat_tradition',
  'indifference',
  'negation',
  'measure',
  'conditional',
  'possession',
  'comparison',
  'origin',
  'absence',
  'sensory',
  // Was `craft` ("the feature as a made thing"). Live output showed it collapsing into `origin` —
  // "was crafted for X, not for Y" beside "was built for X, not for Y" — so the catalog itself was
  // producing the repetition. `consequence` is a genuinely different construction.
  'consequence',
  'paradox',
  'imperative',
];

/** How the feature stands toward the day. Left free, the model made all fifteen features RESIST. */
export const PULSE_STANCES: readonly string[] = ['agrees', 'resists', 'ignores', 'exposes'];

/** Fisher–Yates over `n`, seeded by a string. Same idiom as the feature rotation in `pulse.ts`. */
function permute(n: number, seed: string): number[] {
  const out = Array.from({ length: n }, (_, i) => i);
  for (let i = n - 1; i > 0; i--) {
    const j = fnv1a(`${seed}:${i}`) % (i + 1);
    [out[i], out[j]] = [out[j], out[i]];
  }
  return out;
}

/** The shape + stance this feature writes in today. Deterministic: same (feature, date) → same pair. */
export function pulseComposition(featureKey: string, date: string): { shape: string; stance: string } {
  const i = PULSE_FEATURE_KEYS.indexOf(featureKey);
  const slot = i < 0 ? fnv1a(featureKey) % PULSE_SHAPES.length : i % PULSE_SHAPES.length;
  return {
    shape: PULSE_SHAPES[permute(PULSE_SHAPES.length, `shape:${date}`)[slot]],
    stance: PULSE_STANCES[fnv1a(`stance:${date}:${featureKey}`) % PULSE_STANCES.length],
  };
}

export interface PulseInput {
  date: string;
  featureKey: string;
  /** The DATE's own pillar (甲子), element (wood…) and branch animal (Rat…) — context, not a bucket. */
  dayPillar: string;
  element: string;
  animal: string;
  locale: string;
  systemInstruction: string;
  geminiCall: GeminiCall;
}

export type PulseResult =
  | { ok: true; content: Record<string, unknown>; usage?: GeminiResponse['usageMetadata'] }
  | { ok: false; failureReason: string; detail?: string };

export function buildPulseRequest(input: PulseInput): Record<string, unknown> {
  const { shape, stance } = pulseComposition(input.featureKey, input.date);
  const payload = {
    date: input.date,
    feature_key: input.featureKey,
    feature_label: FEATURE_LABEL[input.featureKey] ?? input.featureKey,
    day_pillar: input.dayPillar,
    element: input.element,
    animal: input.animal,
    locale: input.locale,
    // The two anti-convergence axes (see PULSE_SHAPES). The model cannot diversify across calls it
    // cannot see, so the caller hands it a construction and a stance it did not choose.
    shape,
    stance,
  };
  return {
    systemInstruction: { parts: [{ text: input.systemInstruction }] },
    contents: [{ role: 'user', parts: [{ text: `Write today's line for:\n${JSON.stringify(payload)}` }] }],
    generationConfig: {
      temperature: 0.4,
      seed: PULSE_SEED,
      responseMimeType: 'application/json',
      responseSchema: toGeminiSchema(pulseSchema as Record<string, unknown>),
    },
  };
}

type ValidateFn = ((d: unknown) => boolean) & { errors?: unknown };
type AjvInstance = { compile(s: unknown): ValidateFn; errorsText(e?: unknown): string };
const Ajv = AjvDefault as unknown as new (o?: Record<string, unknown>) => AjvInstance;
const ajv = new Ajv({ allErrors: true, strict: false });
const validatePulse = ajv.compile(pulseSchema);

/** The free line must actually name the feature — it is the entire free tier of this surface. */
export function essenceNamesFeature(essence: string, featureKey: string): boolean {
  const label = (FEATURE_LABEL[featureKey] ?? featureKey).toLowerCase();
  const text = essence.toLowerCase();
  // Accept the label, its head noun ("heart line" → "heart"), or the raw key with _ as a space.
  const head = label.split(' ')[0];
  return text.includes(label) || text.includes(head) || text.includes(featureKey.replace(/_/g, ' '));
}

/**
 * Does the free line name the day? (RF6.T1 rule zero.)
 *
 * The whole reframe is that the palm did not change today — the day did — so the day is the light
 * the feature is read in and never the subject of the one line every reader sees. A prompt rule
 * with no enforcement leaks: v2's first live run put "this Fire day" into 1 of 15 essences, and the
 * nightly cron has no human reading its output. `reading` may name the day; `essence` may not.
 */
export function essenceNamesDay(essence: string, day: { element: string; animal: string; dayPillar?: string }): string | null {
  const low = essence.toLowerCase();
  // Spelled out rather than suffixed: the adjective forms are irregular (`fire` → `fiery`, not
  // `firey`; `metal` → `metallic`), so a `(y|en)?` guess silently misses the exact word the model
  // reaches for. Word-bounded throughout, so `fired clay` and `metallurgy` do not trip it — the
  // rule is about NAMING the day, not about banning a syllable.
  const forms = ELEMENT_FORMS[day.element.toLowerCase()] ?? [day.element.toLowerCase()];
  if (new RegExp(`\\b(${forms.join('|')})\\b`).test(low)) return day.element;
  if (new RegExp(`\\b${day.animal.toLowerCase()}s?\\b`).test(low)) return day.animal;
  if (day.dayPillar && essence.includes(day.dayPillar)) return day.dayPillar;
  return null;
}

const ELEMENT_FORMS: Record<string, string[]> = {
  wood: ['wood', 'wooden', 'woody'],
  fire: ['fire', 'fiery', 'firey'],
  earth: ['earth', 'earthen', 'earthy'],
  metal: ['metal', 'metallic'],
  water: ['water', 'watery'],
};

export async function generatePulse(input: PulseInput): Promise<PulseResult> {
  const res = await input.geminiCall(buildPulseRequest(input));
  const cand = res.candidates?.[0];
  const finish = cand?.finishReason;
  if (finish && finish !== 'STOP') return { ok: false, failureReason: `gemini_finish_${finish.toLowerCase()}` };

  const text = cand?.content?.parts?.map((p) => p.text ?? '').join('') ?? '';
  let content: Record<string, unknown>;
  try {
    content = JSON.parse(text);
  } catch {
    return { ok: false, failureReason: 'invalid_json', detail: text.slice(0, 120) };
  }
  if (!validatePulse(content)) return { ok: false, failureReason: 'schema_invalid', detail: ajv.errorsText(validatePulse.errors) };

  const scan = [content.essence, content.reading, content.career, content.love, content.wealth, content.watch, content.chapter_tone].join('\n');
  const hits = bannedHits(scan);
  if (hits.length) return { ok: false, failureReason: 'content_safety', detail: hits.join(',') };

  // The one content rule the schema cannot express. A generic essence ("A day that favors
  // patience.") would silently turn the personalized surface back into a horoscope — the exact
  // failure this whole feature exists to avoid — so it is a REJECT, not a warning.
  if (!essenceNamesFeature(String(content.essence), input.featureKey)) {
    return { ok: false, failureReason: 'essence_generic', detail: String(content.essence).slice(0, 90) };
  }

  // Rule zero, enforced where the content is actually made rather than only where I happen to be
  // watching. A rejected feature is reported missing and the (idempotent) re-run retries it.
  const named = essenceNamesDay(String(content.essence), { element: input.element, animal: input.animal, dayPillar: input.dayPillar });
  if (named) return { ok: false, failureReason: 'essence_names_day', detail: `${named} — ${String(content.essence).slice(0, 90)}` };

  return { ok: true, content, usage: res.usageMetadata };
}

// ── One day's fan-out ────────────────────────────────────────────────────────────────────────────

export interface PulseFailure {
  featureKey: string;
  reason: string;
  detail?: string;
}
export interface PulseDayInput {
  date: string;
  locale: string;
  dayPillar: string;
  element: string;
  animal: string;
  systemInstruction: string;
  featureKeys?: readonly string[];
  geminiCall: GeminiCall;
  /** Feature keys already stored for (date, locale) — skipped unless `force`. */
  existing: () => PromiseLike<string[]>;
  upsert: (featureKey: string, content: Record<string, unknown>) => PromiseLike<{ error: unknown }>;
  concurrency?: number;
  force?: boolean;
}
export interface PulseDayResult {
  date: string;
  locale: string;
  total: number;
  skipped: number;
  generated: number;
  failed: number;
  /** The feature keys still absent after this run. Empty ⇔ the day is complete. */
  missing: string[];
  failures: PulseFailure[];
}

/** The day is complete only when nothing is missing. The handler MUST NOT return 200 otherwise. */
export function pulseDayComplete(r: PulseDayResult): boolean {
  return r.missing.length === 0;
}

export async function generatePulseDay(input: PulseDayInput): Promise<PulseDayResult> {
  const keys = input.featureKeys ?? PULSE_FEATURE_KEYS;
  const limit = Math.max(1, input.concurrency ?? PULSE_CONCURRENCY);
  const done = input.force ? new Set<string>() : new Set(await input.existing());
  const todo = keys.filter((k) => !done.has(k));
  const failures: PulseFailure[] = [];
  let generated = 0;
  let cursor = 0;

  // A worker pool over a shared cursor — `limit` in flight, no wave barrier, so one slow feature
  // never idles the rest. Safe without a lock: the read-and-increment has no await inside it.
  const worker = async (): Promise<void> => {
    for (;;) {
      const i = cursor++;
      if (i >= todo.length) return;
      const featureKey = todo[i];
      try {
        const r = await generatePulse({
          date: input.date,
          featureKey,
          dayPillar: input.dayPillar,
          element: input.element,
          animal: input.animal,
          locale: input.locale,
          systemInstruction: input.systemInstruction,
          geminiCall: input.geminiCall,
        });
        if (!r.ok) {
          failures.push({ featureKey, reason: r.failureReason, detail: r.detail });
          continue;
        }
        const { error } = await input.upsert(featureKey, r.content);
        if (error) {
          failures.push({ featureKey, reason: 'upsert_failed', detail: errText(error) });
          continue;
        }
        generated++;
      } catch (e) {
        // Best-effort per feature — one bad feature must not abort the other 14 — but the failure is
        // NAMED and surfaced rather than swallowed into a counter (the M3 lesson).
        failures.push({ featureKey, reason: 'unhandled', detail: errText(e) });
      }
    }
  };
  await Promise.all(Array.from({ length: Math.min(limit, todo.length) }, worker));

  return {
    date: input.date,
    locale: input.locale,
    total: keys.length,
    skipped: keys.length - todo.length,
    generated,
    failed: failures.length,
    missing: failures.map((f) => f.featureKey).sort(),
    failures,
  };
}

function errText(e: unknown): string {
  if (e instanceof Error) return e.message;
  if (e && typeof e === 'object' && 'message' in e) return String((e as { message: unknown }).message);
  return String(e);
}
