-- H5 + M12(b) (ledger B10) — chat history ordering and persisted citations.

-- ── M12(b) — citations exist only in the HTTP response, never at rest ────────────────────────────
-- chat-send returns `citations` in its JSON body but persists only thread_id/role/content/tokens,
-- and `chat_messages` has no column for them (`grep -ric citation supabase/migrations/` → 0 hits).
-- So the "cites your heart line…" trust line — the thing that makes a grounded answer legible as
-- grounded rather than as a chatbot guess — survives exactly as long as the response is on screen.
-- Reload the thread and it is gone. Additive; the client half is P6 wiring.
alter table public.chat_messages add column if not exists citations jsonb;

comment on column public.chat_messages.citations is
  'Grounding the assistant turn cited (feature_keys / KB chunks), persisted so a reloaded thread '
  'keeps its trust line instead of degrading to an ungrounded-looking answer (audit M12b).';

-- ── H5 — the model is fed the EIGHT OLDEST turns, forever ────────────────────────────────────────
-- chat-send/index.ts:96 reads `.order('created_at', {ascending: true}).limit(8)`, so any thread past
-- 8 messages converses against its first 8 for the rest of its life. (`chat.ts:149`'s `slice(-8)` is
-- a no-op — the list is already ≤8 — so the order clause is the whole bug.)
--
-- The audit's fix is "order descending + limit + reverse", but that alone is NOT deterministic here,
-- and this migration is what makes it so:
--   * `id` is `gen_random_uuid()` — random, so it cannot break a tie;
--   * `created_at` defaults to `now()`, which is transaction_timestamp() — CONSTANT within a
--     transaction (verified on staging: `select now() = now()` → true);
--   * chat-send inserts the user AND assistant rows of a turn in ONE statement, so they receive an
--     IDENTICAL created_at.
-- Ordering by created_at therefore cannot distinguish a turn's question from its answer: their
-- relative order is undefined, and "most recent 8" could hand the model [assistant, user] — a
-- corrupted conversation. A monotonic sequence gives the ordering an unambiguous key.
--
-- Safe to add: chat_messages is empty on staging (0 rows, verified), so there is nothing to backfill
-- and no existing row whose order we would be inventing.
alter table public.chat_messages add column if not exists seq bigint generated by default as identity;

comment on column public.chat_messages.seq is
  'Monotonic insert order within a thread. created_at CANNOT order a turn: now() is constant per '
  'transaction and chat-send inserts both rows of a turn in one statement, so they share a '
  'timestamp, and the uuid pk is random. This is the ordering key for "the most recent N turns" '
  '(audit H5).';

-- The existing index is (thread_id, created_at) — useless for the new ordering. This one serves
-- `where thread_id = ? order by seq desc limit 8` as an index-only backwards scan.
create index if not exists chat_messages_thread_id_seq_idx
  on public.chat_messages (thread_id, seq desc);
